version: "3"

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"

  webserver:
    restart: always
    build:
      context: ./webserver
    ports:
      - "80:80"

  database:
    image: postgres:15-alpine3.19
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/user
      POSTGRES_PASSWORD_FILE: /run/secrets/pass
      POSTGRES_DB_FILE: /run/secrets/db
    secrets:
      - user
      - pass
      - db
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
      - "6000:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'haeckal@bangkit.com'
      PGADMIN_DEFAULT_PASSWORD: 'testing'
    ports:
      - 8000:80
    volumes:
      - ./database/servers.json:/pgadmin4/servers.json

secrets:
  user:
    file: ./database/user.txt
  pass:
    file: ./database/password.txt
  db: 
    file: ./database/dbname.txt

volumes:
  pgdata:
